kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"maven-app:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"maven-app\")].image"}]
    openshift.io/generated-by: OpenShiftNewApp
  name: maven-app
  namespace: dev
  labels:
    app: maven-app
    app.kubernetes.io/component: maven-app
    app.kubernetes.io/instance: maven-app
spec:
  replicas: 2
  selector:
    matchLabels:
      deployment: maven-app
  template:
    metadata:
      labels:
        deployment: maven-app
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: maven-app
          image: >-
            image-registry.openshift-image-registry.svc:5000/dev/maven-app@sha256:7ff3b075b8aa33b48afb134987ffc73043510c8ba704e28d51cd8323fc1fa4a9
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
