kind: Service
apiVersion: v1
metadata:
  name: maven-app
  labels:
    app: maven-app
    app.kubernetes.io/component: maven-app
    app.kubernetes.io/instance: maven-app
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    deployment: maven-app
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
