apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dotnet-app-gitops
  namespace: cicd
spec:
  destination:
    namespace: dev
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: dotnet-app
    repoURL: 'https://github.com/osa-ora/gitops-sample'
    targetRevision: main
  syncPolicy:
    automated: {}
