kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-role-binding-for-dev
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: argocd-argocd-application-controller
    namespace: cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-manager-role
