
   
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: serverless-maven-app-gitops
spec:
  destination:
    namespace: dev
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: maven-app-serverless
    repoURL: 'https://github.com/osa-ora/gitops-sample'
    targetRevision: main
  syncPolicy:
    automated: {}
