apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: serverless-maven-app
spec:
  template:
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/dev/maven-app
